### ISSUE TITLE
Error message required in cart  when the coupon code is blank

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#12]
Steps:
1.Add items to the cart and and click on view cart.
2. Leave the coupon code blank and click on apply coupon
 Current behaviour: No error message is given when the coupon code is left blank
Expected behaviour: An apptropriate error message has t be given when the  coupon field is blank and apply coupon is clicked.

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested.
