### ISSUE TITLE
Difficult to bring the focus on the 'view cart' button 

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#13]
Steps: 
1.Hover on the Cart icon 
2.Try to click on the 'view cart' button by moving the cursor diagonally downward in the drop down
Current behaviour: The drop down closes if the user moves the cursor diagonally down towards the 'View cart button'
Expected behaviour: The drop down should not close until the cursor is on any part of the dropdown

**Comment by robiulpro** [comment]
Works as expected.
