### ISSUE TITLE
Orders screen shows wrong count

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#15]
The different filters(Based on order status) on the order screen for admin shows wrong count.
Similarly the label 'Order' under Woocommerce shows the wrong count.

**Comment by anujkhurana** [comment]
To be discussed. Please come to my desk on Friday morning and lets decide
how we will solve this.

**Comment by robiulpro** [comment]
Customized the order count. The condition is below:
Status - 'All':  count only parent order items, but display all orders grouped with 'show sub-orders' option.
Remaining Status: count only actual order items with specific status (excludes parent, if any), display same.

**Comment by ashika123** [comment]
The admin side displays a wrong count
