### ISSUE TITLE
Updating the seller gives incorrect error messages

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#17]
Steps:
1. Login as admin,Open sellers and click on edit
2. make changes in the seller details(Changed the address)
3. Click on update seller

Current behaviour: Two error messages are displayed
'seller updated' and 'ERROR: Please enter an e-mail address.'
Expected: Appropriate error message has to be displayed.

**Comment by robiulpro** [comment]
Fixed

**Comment by ashika123** [comment]
Tested. Fixed
