### ISSUE TITLE
Seller does not get a mail intimation when order is placed

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#20]
Steps: 
1. Order is placed for items of the seller(theseller@mailinator.com)
Current behaviour: mail is sent to admin and the customer however the seller does not receive any mail about the order
Expected behaviour: Seller has to receive mail about the orders placed for his product

**Comment by robiulpro** [comment]
Completed.

**Comment by ashika123** [comment]
Tested. Issues have been reported.

**Comment by robiulpro** [comment]
@ashika123  refer the issue number.
