### ISSUE TITLE
Mail is not send to the admin,seller and customer when status of the order is changed

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#21]
Steps:
1. Login as admin and change the status of the order
2.Check mailboxes for admin, customer and the seller

current behaviour: Mails are not sent when the status of the order is changed 
expected behaviour: Mails have to be send when the status of the order is changed

**Comment by anujkhurana** [comment]
Let's discuss how we will implement seller specific emails and take care of all the emails. 

http://docs.woothemes.com/document/configuring-woocommerce-settings/ The email section on this link has all the emails.

**Comment by robiulpro** [comment]
Completed. On status change, customer and admin gets same email. Specific subject and header for part order.

**Comment by ashika123** [comment]
Tested. Issues reported.
