### ISSUE TITLE
Filters not shown for sellers on order screen

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#23]
Steps: 
1.Login as a seller.
2. Click on Orders
Current Behaviour: No filters are visible to the user
Expected Behaviour: The filters have to be visible to the user

**Comment by anujkhurana** [comment]
@Robiul how difficult would this be?

Let's not do this for now. We can come back to it later.

**Comment by robiulpro** [comment]
Fixed

**Comment by ashika123** [comment]
tested.
