### ISSUE TITLE
Order discount is not shown to the sellers when order includes multiple sellers

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#24]
![discount](https://cloud.githubusercontent.com/assets/9797052/5595027/0724af64-928e-11e4-8c26-acfb1af85a8b.png)
When coupon discount is applied on the order, Sellers are not shown the order discount in the order discount field when there are multiple sellers in one order
( Also applicable on front end for the subscriber login.)
Steps:
1. Add items to cart belonging to 2 sellers.
2.Apply coupon discount on it.
3.Place the order.

Current behaviour: The sellers are not shown the order discount(Order status-Onhold)
Expected behaviour:Order discount has to be shown to the sellers.

**Comment by anujkhurana** [comment]
Good catch.

**Comment by robiulpro** [comment]
Coupons are added by site admin as the discount is site level. That's why in seller part of the order, no discount applies.
