### ISSUE TITLE
Orders are not displayed for the filters

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#25]
Steps: 
1. Login as admin and click on the filter Completed order/ Cancelled orders.

 Current behaviour; The orders for this filters are shown when the page is getting loaded for a short time and then are not displayed when the page is completely loaded.
Expected Behaviour: The orders have to be displayed when the filters are clicked.

**Comment by robiulpro** [comment]
@ashika123 , can you recheck, the issue is not exist.

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested.
