### ISSUE TITLE
Blank message displayed when two coupons are applied on checkout

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#26]
steps:
1. Add items to the cart and go to checkout.
2. Apply the first coupon and then when the message is still displayed 'Coupons applied successfully' apply the second coupon.

Current behaviour: The second message shown is blank.
Expected behaviour: The message has to be shown to the user.

![coupon](https://cloud.githubusercontent.com/assets/9797052/5609325/b8ad9192-94c3-11e4-83b4-4025b326b95e.png)

**Comment by robiulpro** [comment]
Unable to recreate the scenario. Works fine.

**Comment by ashika123** [comment]
This behaviour is seen on the checkout page,works fine in cart.

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested.
