### ISSUE TITLE
Reports shown for all the sellers and the admin are the same

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#28]
Steps: 
1. Login as seller 
2. Click on Reports under Woocommerce
3. Repeat by logging in as Admin

Current Behaviour:The reports shown for all the sellers and the admin are the same
Expected Behaviour:Reports for sellers should display only the sales for that particular seller.

**Comment by anujkhurana** [comment]
I thought this was working before? Did any recent change cause this bug? Please put in the comments what caused the bug and how it was fixed.

**Comment by robiulpro** [comment]
It was not done.

**Comment by anujkhurana** [comment]
Let's remove the reports for sellers.

**Comment by robiulpro** [comment]
Removed.
