### ISSUE TITLE
when Clicked on the product image, it  is opened on two different screens

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#30]
Steps:
1. Click on the product image.
2.Close the image.

Current behaviour: 1.After closing this image, one more image screen is visible to the user.
2. the close button on this(second screen) image is hidden if the image occupies the entire screen.

Expected behaviour: Only one image screen has to be visible 

![image](https://cloud.githubusercontent.com/assets/9797052/5613027/e80dc0de-9503-11e4-871e-e0486657df70.png)

**Comment by robiulpro** [comment]
@amit0773 , can you please take a look, it seems some plugin lightbox script is conflicting with themes lightbox.

**Comment by amit0773** [comment]
this is done
