### ISSUE TITLE
The phone number field on checkout shows names of the sellers in dropdown

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#31]
Steps:
1. Add items to cart and click on Checkout.

Current behaviour: The phone number field shows the names of the sellers in the drop down.
Expected behaviour: No drop down should be shown for the phone number field.
![checkout foods tree](https://cloud.githubusercontent.com/assets/9797052/5659621/35422ed8-973b-11e4-9eb6-49b4c936fd97.png)

**Comment by robiulpro** [comment]
@ashika123 clear your browser data. The issue is user specific.

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested
