### ISSUE TITLE
Account password field on checkout gets auto-populated

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#32]
Steps:
1. Add items to cart and click on checkout.
2.Fill in all the details on the form 
3.Check the check box 'Create an account'

Current Behaviour: The account password field gets auto-populated
Expected Behaviour:The account password field should not get auto-Populated.
 
![actpasword](https://cloud.githubusercontent.com/assets/9797052/5659665/0e522cbe-973c-11e4-966b-fc3ceb876acb.png)

**Comment by robiulpro** [comment]
@ashika123  clear your browser data. Nothing to do with the code.

**Comment by anujkhurana** [comment]
@Ashika leave the task open. I will figure out why this happens.

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested.
