### ISSUE TITLE
Validation required on Phone number and postcode field

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#33]
steps:
1. Add items to the cart
2. Click on  checkout.
Current behaviour: The postcode and phone number field accepts alphabets
Expected Behaviour:Postcode and phone number field should only allow numbers
![phone_post](https://cloud.githubusercontent.com/assets/9797052/5659697/f00b2e8a-973c-11e4-8aa4-82e5cbb15f5a.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested.
