### ISSUE TITLE
Seller does not receive complete mail when a new customer is registered

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#34]
steps:
1. Add items to the cart
2.Check the box 'Create an account'
3. Click on place order.

Current behaviour:The mail sent to the seller is incomplete when new customer account is created..The order details are not displayed to the seller.
Expected Behaviour:The seller should receive a complete mail.
![seller_new customer](https://cloud.githubusercontent.com/assets/9797052/5660296/b164f230-9744-11e4-89d2-ada1dd1c4439.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested.
