### ISSUE TITLE
Order status in the seller dashboard and the customer's mail does not match

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#35]
Steps:
1. Place a order. Check the mail received on placing the order
2.Login as seller Click on orders and check for the status of order just placed.

Current behaviour:The mail says the order status as 'processing' but is shown as 'on hold' to the seller
Similarly the status of the order for customer(In the front end) is shown as 'On hold'
Expected Behaviour: The status of the order has to be same in the mail and on seller's order screen 

![order stastus](https://cloud.githubusercontent.com/assets/9797052/5661860/ed01df76-9756-11e4-9df1-768b3200904a.png)

**Comment by robiulpro** [comment]
When order placed and if the payment method is check/bank transfer, customer receives new order mail with following contents:
-----------------------------------------------------------------------------------
"Your order has been received and is now being processed. Your order details are shown below for your reference:

Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account."
-----------------------------------------------------------------------------

'being processed' doesn't represents the actual status of order. In back-end 'on-hold' is for admin/seller reference, but for customer, the order is placed and need to complete the payment.
