### ISSUE TITLE
Mails are not sent on change of order status except for 'Completed'

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#36]
Steps:
1. Login as seller, Change the status of the order as 'Processing'

Current behaviour: The mails are sent to admin and the customer only when the status of the order is changed to completed.
Expected Behaviour: The mails have to be sent to the customer and the admin on all status changes.

**Comment by robiulpro** [comment]
Customer receives mails automatically when:
1. New registration
2. New order
3. Customer note added to order 
4. Order marked as completed

In order edit page, there is option to send/resend some emails manually to customer:
1. New order
2. Processing order
3. Completed order
4. Customer invoice
5. Generate download permission (for downloadable products)

'Order status' on order edit page is for admin/seller reference. When you changing status 'on hold' to 'processing', you can send 'processing' mail manually by clicking on appropriate option under 'Order actions'.
