### ISSUE TITLE
Inconsistent behaviour is shown when the images are uploaded on sellers profile

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#41]
Steps:
1. Login as admin Click on seller
2. Click on edit for any seller and upload files under uploads

Current behaviour:Image uploaded is shown on the right only for the 'company logo' field
Expected behaviour: Has to have a consistent behaviour for all the fields
![add_prop](https://cloud.githubusercontent.com/assets/9797052/5735911/758f596c-9bf4-11e4-9d7f-d033c9991583.png)

**Comment by robiulpro** [comment]
PAN registration copy, Cancelled cheque and TAN registration copy can be any document type, where logo is always image type. That's why it was done purposely, admin can download these three document by clicking on respective button.
