### ISSUE TITLE
Additional properties for the seller are visible only to admin

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#42]
Steps:
1. Login as seller and click on profile

Current behaviour:The additional properties for the seller are not displayed on sellers profile page
expected behaviour:All the properties for the seller has to be visible to the seller.

**Comment by robiulpro** [comment]
I will be working on the custom profile template page for seller. Is all fields are editable from seller end?

**Comment by robiulpro** [comment]
Completed

**Comment by ashika123** [comment]
Tested. All the fields made editable to the seller.
