### ISSUE TITLE
Error message when .gif image is uplaoded

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#43]
Steps:
1.Login as admin, Click on seller
2. Under uploads upload a .gif image for any field

Current behaviour: Message shown as in the screen shot is displayed
Expected behaviour: .gif images should be allowed to be uploaded
![error_gif](https://cloud.githubusercontent.com/assets/9797052/5736949/e1212c02-9c01-11e4-8c2a-804ef3a72c09.png)

**Comment by robiulpro** [comment]
Server specific issue. Works fine on localhsot and wp-engine.
