### ISSUE TITLE
Error when setting featured images

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#44]
Steps:
1. Click on products and then add products
2. Click on set featured image and then upload files
3. Upload image in .gif and then .tiff formats
 Current behaviour: Error is thrown when .gif image is uploaded and .tiff image is not visible when uploaded
Expected behaviour: .gif and .tif  formats have to be supported.
![giferror](https://cloud.githubusercontent.com/assets/9797052/5737300/3d10a79c-9c05-11e4-849b-2e7fc1cafb7e.png)

![tifferror](https://cloud.githubusercontent.com/assets/9797052/5737308/5c16d288-9c05-11e4-99d1-9ac52642bf4d.png)

**Comment by robiulpro** [comment]
The issue only with .gif file and only on test server (dreamhost). I have tested with localhost and wp-engine, it seems all fine.

**Comment by robiulpro** [comment]
.tiff is not the standard image type for all browser. So displaying .tiff image is browser specif. Here is the complete list of browser supports .tiff image format: http://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support
