### ISSUE TITLE
Update seller button required at the top of the page too on edit seller page

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#45]
Current behaviour: on the edit seller page (on admin side)User has to scroll down to the bottom of the page to update the seller details
Expected Behaviour:The update seller button on the edit seller page is required both at the bottom and also at the top of the page
![update seller](https://cloud.githubusercontent.com/assets/9797052/5737437/b93e647a-9c06-11e4-9267-ddbe4b4b0e58.png)

**Comment by robiulpro** [comment]
Completed

**Comment by ashika123** [comment]
Tested.
