### ISSUE TITLE
Numeric validation check required on pincode, phone number and account number field for seller page

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#47]
Steps:
1.Login as admin
2.Click on seller and then add new seller

Current behaviour: The fields accept any data 
Expected: Phone number, pincode and account number fields should only accept numbers

**Comment by robiulpro** [comment]
Fixed

**Comment by ashika123** [comment]
This behaviour is not seen on the admin side.
On sellers side pincode field under billing address does not show this behaviour

**Comment by robiulpro** [comment]
FIxed

**Comment by ashika123** [comment]
Tested
