### ISSUE TITLE
Subtitle for grouping seller's information is required on edit seller page

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#48]
Steps:
1.Login as admin and click on seller 
2. Edit any of the seller
Current behaviour: The seller information currently is shown below the subtitle 'Pincode Info'
Expected Behaviour: A subtitle is required to group the seller's info fields
![grouping](https://cloud.githubusercontent.com/assets/9797052/5738196/7fb63f1c-9c0f-11e4-85c5-88e91f863620.png)

**Comment by robiulpro** [comment]
Completed

**Comment by ashika123** [comment]
Tested. Subtitle given is 'Personal Info'
