### ISSUE TITLE
Consistent formatting required for the labels of all fields

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#49]
-The edit seller page

current behaviour: Both the words for some labels are capitalised whereas some its not
Expected behaviour: Label format has to be consistent. Let only the first letter be in caps.(Except when the word demands to be in caps) 
![formatting](https://cloud.githubusercontent.com/assets/9797052/5738372/82b051ec-9c11-11e4-92bf-7072216dcbe2.png)

**Comment by robiulpro** [comment]
Completed

**Comment by ashika123** [comment]
Tested.
