### ISSUE TITLE
Logout from wordpress diverts to a different link

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#5]
Steps
1. Login to 
http://foodstree.com/wp-admin/index.php
2. Then Logout

Current behaviour: On logout user is diverted to the ajency site
Expected Behaviour: User has to be diverted to the Login page

**Comment by robiulpro** [comment]
Multisite issue, works fine on test site. Also all user should not redirect to login page. For example if user (usually 'customer')  logged out from frontend, he should redirect to site route, instead of login page.

**Comment by anujkhurana** [comment]
@ashika : please test on test site only for now. Main site will need to be
moved to different location.

**Comment by ashika123** [comment]
Ok
