### ISSUE TITLE
Text colour on the seller profile page after the error message

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#50]
Steps:
1 Login as admin and click on seller
2.Then add new seller.
4. Let the mandatory fields be blank and click on 'Add new seller'
A similar behaviour is shown on sellers profile page.
Current behaviour:The colour of the text typed is red till the error message message disappears.
Expected Behaviour:The text color should be in blank always
![text colour](https://cloud.githubusercontent.com/assets/9797052/5774734/f4eb0ffa-9d96-11e4-96df-1bd9397ec462.png)

**Comment by robiulpro** [comment]
Expected behavior in validation and this is how validate.js works. The text turns red to black when you start typing.
