### ISSUE TITLE
Single coupon applied on checkout cannot be removed 

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#53]
Steps:
1, Add item to the cart 
2.Click on proceed to checkout
3.Apply coupon from the checkout page and then remove the coupon by clicking on the remove link

Current behaviour:when clicked on 'remove' the coupon is not removed
expected Behaviour:The remove link should remove the applied coupon

**Comment by robiulpro** [comment]
It works fine.

**Comment by robiulpro** [comment]
@ashika123 ,do not use '#' in coupon code as it conflicts with javascript.
