### ISSUE TITLE
Error while creating a seller if the 'Check if billing address same as registered address' is checked

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#72]
Steps:
1 Create a new seller
2.Check the field 'Check if billing address same as registered address' field
3. Enter the passwords such that there is mismatch 

Current behaviour: On entering the correct password the field 'Check if billing address same as registered address' stays checked and the fields below it are also displayed
Expected behaviour:The fields under shipping address should not be displayed if 'Check if billing address same as registered address' is checked.
![testsite](https://cloud.githubusercontent.com/assets/9797052/6104641/559a23ae-b075-11e4-90b7-32648117183b.png)

**Comment by robiulpro** [comment]
FIxed.

**Comment by ashika123** [comment]
Tested
