### ISSUE TITLE
Categories on the side bar show count zero

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#77]
The categories on the side bar show count as zero
Expected behaviour: The Count of the products belonging to the category has to be displayed.
![live_cat_zero](https://cloud.githubusercontent.com/assets/9797052/6141818/f8d0af46-b1d0-11e4-80b6-cb49ab0fd4a7.png)

**Comment by robiulpro** [comment]
@ashika123 , the count is zero because there is no products available for your pincode. Click on "View products from all sellers" option, you'll get proper count.

**Comment by ashika123** [comment]
ok.
