### ISSUE TITLE
Clicking on 'add to cart' does work on the product image

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#78]
Steps:
1. Hover on the product image, will display the add to cart 
2. Click on 'add to cart

Current behaviour: The add to cart does not add product to cart
Expected behaviour: The product has to be added to the cart.
![add to cart](https://cloud.githubusercontent.com/assets/9797052/6141889/707c1e58-b1d2-11e4-9ca5-6df0134661de.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by ashika123** [comment]
Tested
