### ISSUE TITLE
Quantity of the product can be reduced to zero when in cart

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#8]
The quantity of the product can be reduced to zero when the product is in cart.

Steps: 
1.Add a product to the cart.
2. Click on view cart
3,Decrement the counter
Current behaviour: The counter reduces to 0
Expected behaviour: The counter should have 1 as the least value

**Comment by robiulpro** [comment]
Default behavior in woocommerce. When quantity is zero, the product will be removed from cart when click on update button.
