### ISSUE TITLE
Error view when clicked on place order

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#9]
Steps : 
1.Add items to the cart and click on ' proceed to checkout'
2. On check out page Click on 'place order'
Current behaviour: error view is shown as in attached image 
Expected behaviour: Place order has to be disabled until mandatory fields are filled
![place order](https://cloud.githubusercontent.com/assets/9797052/5576769/ebbafb64-9028-11e4-9751-f9ba5565b253.png)

**Comment by robiulpro** [comment]
This is the way woocommerce works. Hiding place order button is not recommended.

**Comment by ashika123** [comment]
ok
